import Accordion from './accordion.JPG'
import Aninav from './animatednav.JPG'
import Slideback from './backgroundslide.JPG'
import Birthday from './birthday.JPG'
import Blur from './blur.JPG'
import Buttonripple from './buttonripple.JPG'
import Cart from './cart.JPG'
import Cocktail from './coctail.JPG'
import Color from './color.JPG'
import Colorgenerator from './colorgenerator.JPG'
import Comfy from './comfy.JPG'
import Darkmode from './darkmode.JPG'
import Dragdrop from './dragdrop.JPG'
import Expandcard from './expandcard.JPG'
import Github from './github.JPG'
import Imagegallery from './imagegallery.JPG'
import Lorem from './lorem.JPG'
import Markdown from './markdown.JPG'
import Menu from './menu.JPG'
import Movie from './movie.JPG'
import Navbar from './navbar.JPG'
import News from './news.JPG'
import Pagination from './pagination.JPG'
import Photostock from './photstock.JPG'
import Progress from './progress.JPG'
import Quiz from './quiz.JPG'
import Randomqa from './randomq&a.JPG'
import Randomuser from './randomuser.JPG'
import Review from './review.JPG'
import Rotatenav from './rotatenav.JPG'
import Search from './search.JPG'
import Sidebar from './sidebar.JPG'
import Slider from './slider.JPG'
import Sound from './sound.JPG'
import Stickynav from './stickynav.JPG'
import Submenu from './submenu.JPG'
import Tab from './tab.JPG'
import Todo from './todo.JPG'
import Todohtml from './todohtml.JPG'
import Tour from './tours.JPG'
import Waveform from './waveform.JPG'
import Yelp from './yelp.png'

export {
    Accordion,Aninav, Birthday, Buttonripple, Blur, Comfy, Colorgenerator, Color, Cocktail, Cart, Dragdrop, Darkmode, Expandcard, Github, Imagegallery, Lorem, Movie, Menu, Markdown, News, Navbar, Pagination, Progress, Photostock, Quiz, Rotatenav, Review, Randomuser, Randomqa, Submenu, Stickynav, Sound, Slider, Slideback, Sidebar, Search, Tour, Todohtml, Todo, Tab, Waveform, Yelp
}